// Document Templates — HTML generators for all document types
// Each template generates a styled HTML document suitable for WebView rendering and PDF export.
// Uses inline CSS for PDF compatibility and Casa branding (Navy #1B1464).

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-AU', {
    style: 'currency',
    currency: 'AUD',
    minimumFractionDigits: 2,
  }).format(amount);
}

function formatDateAU(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

function formatDateShort(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-AU', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

/** Shared document CSS */
const BASE_STYLES = `
  @page { size: A4; margin: 18mm 16mm 22mm 16mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    font-size: 11pt; line-height: 1.5; color: #0A0A0A; background: #fff;
  }
  .doc { max-width: 210mm; margin: 0 auto; padding: 20px; }
  .header { text-align: center; padding-bottom: 16px; margin-bottom: 20px; border-bottom: 2px solid #1B1464; }
  .header h1 { font-size: 18pt; font-weight: 700; color: #1B1464; margin-bottom: 4px; }
  .header .sub { font-size: 10pt; color: #525252; }
  .section { margin-bottom: 20px; page-break-inside: avoid; }
  .section h2 { font-size: 12pt; font-weight: 700; color: #1B1464; margin-bottom: 10px; padding-bottom: 3px; border-bottom: 1px solid #E5E5E5; }
  table.dt { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  table.dt td { padding: 5px 10px; border: 1px solid #E5E5E5; font-size: 10pt; vertical-align: top; }
  table.dt td.l { width: 38%; font-weight: 600; color: #525252; background: #F5F5F4; }
  table.dt td.v { color: #0A0A0A; }
  table.dt th { padding: 6px 10px; border: 1px solid #E5E5E5; font-size: 10pt; font-weight: 600; background: #F5F5F4; text-align: left; }
  .note { background: #F5F5F4; border-left: 3px solid #1B1464; padding: 8px 12px; margin: 10px 0; font-size: 9.5pt; color: #525252; }
  .footer { margin-top: 32px; padding-top: 10px; border-top: 1px solid #E5E5E5; text-align: center; font-size: 8pt; color: #A3A3A3; }
  .footer .brand { color: #1B1464; font-weight: 600; }
  p { margin-bottom: 6px; font-size: 10pt; line-height: 1.6; }
  .sig-block { margin-top: 32px; page-break-inside: avoid; }
  .sig-row { display: flex; justify-content: space-between; gap: 32px; margin-bottom: 32px; }
  .sig-party { flex: 1; }
  .sig-party h3 { font-size: 10pt; font-weight: 700; color: #1B1464; margin-bottom: 12px; }
  .sig-line { border-bottom: 1px solid #0A0A0A; height: 36px; margin-bottom: 4px; }
  .sig-label { font-size: 8.5pt; color: #525252; margin-bottom: 16px; }
  .summary-card { background: #FAFAFA; border: 1px solid #E5E5E5; border-radius: 6px; padding: 12px; margin-bottom: 12px; }
  .summary-card .metric { font-size: 20pt; font-weight: 700; color: #1B1464; }
  .summary-card .metric-label { font-size: 9pt; color: #525252; margin-top: 2px; }
  .row { display: flex; gap: 12px; }
  .row .col { flex: 1; }
`;

function wrapDocument(title: string, subtitle: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>${BASE_STYLES}</style>
</head>
<body>
<div class="doc">
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    <div class="sub">${escapeHtml(subtitle)}</div>
  </div>
  ${body}
  <div class="footer">
    <p>Generated by <span class="brand">Casa</span> &mdash; AI-powered property management</p>
    <p>Generated ${formatDateAU(new Date().toISOString())}</p>
  </div>
</div>
</body>
</html>`;
}

// ============================================================
// Financial Report
// ============================================================

export interface FinancialReportData {
  ownerName: string;
  propertyAddress?: string;
  periodStart: string;
  periodEnd: string;
  totalIncome: number;
  totalExpenses: number;
  netProfit: number;
  incomeBreakdown: Array<{ category: string; amount: number }>;
  expenseBreakdown: Array<{ category: string; amount: number }>;
  occupancyRate?: number;
  notes?: string;
}

export function generateFinancialReportHTML(data: FinancialReportData): string {
  const incomeRows = data.incomeBreakdown
    .map(r => `<tr><td class="v">${escapeHtml(r.category)}</td><td class="v" style="text-align:right">${formatCurrency(r.amount)}</td></tr>`)
    .join('');

  const expenseRows = data.expenseBreakdown
    .map(r => `<tr><td class="v">${escapeHtml(r.category)}</td><td class="v" style="text-align:right">${formatCurrency(r.amount)}</td></tr>`)
    .join('');

  const body = `
    <div class="section">
      <h2>Report Details</h2>
      <table class="dt">
        <tr><td class="l">Owner</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        ${data.propertyAddress ? `<tr><td class="l">Property</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>` : ''}
        <tr><td class="l">Period</td><td class="v">${formatDateShort(data.periodStart)} — ${formatDateShort(data.periodEnd)}</td></tr>
      </table>
    </div>

    <div class="row" style="margin-bottom:16px">
      <div class="col">
        <div class="summary-card">
          <div class="metric" style="color:#16A34A">${formatCurrency(data.totalIncome)}</div>
          <div class="metric-label">Total Income</div>
        </div>
      </div>
      <div class="col">
        <div class="summary-card">
          <div class="metric" style="color:#DC2626">${formatCurrency(data.totalExpenses)}</div>
          <div class="metric-label">Total Expenses</div>
        </div>
      </div>
      <div class="col">
        <div class="summary-card">
          <div class="metric">${formatCurrency(data.netProfit)}</div>
          <div class="metric-label">Net Profit</div>
        </div>
      </div>
    </div>

    ${data.occupancyRate !== undefined ? `
    <div class="summary-card" style="margin-bottom:16px">
      <div class="metric">${data.occupancyRate.toFixed(1)}%</div>
      <div class="metric-label">Occupancy Rate</div>
    </div>` : ''}

    <div class="section">
      <h2>Income Breakdown</h2>
      <table class="dt">
        <tr><th>Category</th><th style="text-align:right">Amount</th></tr>
        ${incomeRows}
        <tr style="font-weight:700"><td class="l">Total Income</td><td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.totalIncome)}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Expense Breakdown</h2>
      <table class="dt">
        <tr><th>Category</th><th style="text-align:right">Amount</th></tr>
        ${expenseRows}
        <tr style="font-weight:700"><td class="l">Total Expenses</td><td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.totalExpenses)}</td></tr>
      </table>
    </div>

    ${data.notes ? `<div class="note">${escapeHtml(data.notes)}</div>` : ''}
  `;

  return wrapDocument(
    'Financial Report',
    `${formatDateShort(data.periodStart)} — ${formatDateShort(data.periodEnd)}`,
    body,
  );
}

// ============================================================
// Tax Report
// ============================================================

export interface TaxReportData {
  ownerName: string;
  financialYear: string;
  properties: Array<{
    address: string;
    rentalIncome: number;
    deductions: Array<{ item: string; amount: number }>;
  }>;
  totalIncome: number;
  totalDeductions: number;
  netRentalIncome: number;
  notes?: string;
}

export function generateTaxReportHTML(data: TaxReportData): string {
  const propertyRows = data.properties.map(prop => {
    const deductionRows = prop.deductions
      .map(d => `<tr><td class="v" style="padding-left:20px">${escapeHtml(d.item)}</td><td class="v" style="text-align:right">${formatCurrency(d.amount)}</td></tr>`)
      .join('');
    const totalDeductions = prop.deductions.reduce((sum, d) => sum + d.amount, 0);

    return `
    <div class="section">
      <h2>${escapeHtml(prop.address)}</h2>
      <table class="dt">
        <tr><td class="l">Rental Income</td><td class="v" style="text-align:right">${formatCurrency(prop.rentalIncome)}</td></tr>
        <tr><td class="l" colspan="2" style="text-align:center;color:#1B1464">Deductions</td></tr>
        ${deductionRows}
        <tr style="font-weight:700"><td class="l">Total Deductions</td><td class="v" style="text-align:right;font-weight:700">${formatCurrency(totalDeductions)}</td></tr>
        <tr style="font-weight:700"><td class="l">Net Income</td><td class="v" style="text-align:right;font-weight:700">${formatCurrency(prop.rentalIncome - totalDeductions)}</td></tr>
      </table>
    </div>`;
  }).join('');

  const body = `
    <div class="section">
      <h2>Summary</h2>
      <table class="dt">
        <tr><td class="l">Owner</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">Financial Year</td><td class="v">${escapeHtml(data.financialYear)}</td></tr>
        <tr><td class="l">Total Rental Income</td><td class="v" style="text-align:right">${formatCurrency(data.totalIncome)}</td></tr>
        <tr><td class="l">Total Deductions</td><td class="v" style="text-align:right">${formatCurrency(data.totalDeductions)}</td></tr>
        <tr style="font-weight:700"><td class="l">Net Rental Income</td><td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.netRentalIncome)}</td></tr>
      </table>
      <div class="note">This report is for record-keeping purposes. Consult a registered tax agent for lodgement with the ATO.</div>
    </div>

    ${propertyRows}
    ${data.notes ? `<div class="note">${escapeHtml(data.notes)}</div>` : ''}
  `;

  return wrapDocument(
    'Rental Property Tax Report',
    `Financial Year ${escapeHtml(data.financialYear)}`,
    body,
  );
}

// ============================================================
// Notice (Breach, Entry, Rent Increase, Termination)
// ============================================================

export type NoticeType = 'breach' | 'entry' | 'rent_increase' | 'termination' | 'vacate';

export interface NoticeData {
  noticeType: NoticeType;
  ownerName: string;
  tenantName: string;
  propertyAddress: string;
  state: string;
  issueDate: string;
  // Breach-specific
  breachDescription?: string;
  remedyDate?: string;
  // Entry-specific
  entryDate?: string;
  entryTime?: string;
  entryReason?: string;
  // Rent increase
  currentRent?: number;
  newRent?: number;
  rentFrequency?: string;
  effectiveDate?: string;
  // Termination
  terminationDate?: string;
  terminationReason?: string;
  // Custom content
  additionalNotes?: string;
}

// ============================================================
// State-Specific Legislation References
// ============================================================

export interface LegislationSection {
  section: string;
  description: string;
}

export interface BondInfo {
  section: string;
  authority: string;
  url: string;
}

export interface NoticePeriods {
  section: string;
  periods: Record<string, number>; // reason → days
}

export interface PrescribedForm {
  type: string;
  formNumber: string;
  url: string;
}

export interface StateLegislation {
  name: string;
  state: string;
  conditionReport: LegislationSection;
  bondLodgement: BondInfo;
  noticeToVacate: NoticePeriods;
  rentIncrease: { section: string; minimumNotice: number };
  breachNotice: { section: string; remedyPeriod: number };
  prescribedForms: PrescribedForm[];
  tribunalName: string;
  tribunalUrl: string;
  authorityName: string;
  authorityUrl: string;
}

const STATE_LEGISLATION: Record<string, StateLegislation> = {
  NSW: {
    name: 'Residential Tenancies Act 2010 (NSW)',
    state: 'NSW',
    conditionReport: {
      section: 's 27',
      description: 'Condition report must be completed before tenant moves in. Two copies to tenant within 7 days.',
    },
    bondLodgement: {
      section: 's 159',
      authority: 'NSW Fair Trading',
      url: 'https://www.fairtrading.nsw.gov.au/housing-and-property/renting/bond',
    },
    noticeToVacate: {
      section: 's 84-107',
      periods: { end_of_fixed_term: 30, no_grounds_periodic: 90, breach: 14, sale: 30, demolition: 30 },
    },
    rentIncrease: { section: 's 41', minimumNotice: 60 },
    breachNotice: { section: 's 87', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Standard Condition Report', url: 'https://www.fairtrading.nsw.gov.au' },
      { type: 'tenancy_agreement', formNumber: 'Standard Form Agreement', url: 'https://www.fairtrading.nsw.gov.au' },
      { type: 'notice_to_vacate', formNumber: 'Termination Notice', url: 'https://www.fairtrading.nsw.gov.au' },
    ],
    tribunalName: 'NSW Civil and Administrative Tribunal (NCAT)',
    tribunalUrl: 'https://www.ncat.nsw.gov.au',
    authorityName: 'NSW Fair Trading',
    authorityUrl: 'https://www.fairtrading.nsw.gov.au',
  },
  VIC: {
    name: 'Residential Tenancies Act 1997 (Vic)',
    state: 'VIC',
    conditionReport: {
      section: 's 35',
      description: 'Condition report must be completed and signed by both parties before or at start of tenancy.',
    },
    bondLodgement: {
      section: 's 406',
      authority: 'Residential Tenancies Bond Authority (RTBA)',
      url: 'https://www.rtba.vic.gov.au',
    },
    noticeToVacate: {
      section: 's 91ZZA-91ZZR',
      periods: { end_of_fixed_term: 60, no_grounds_periodic: 90, breach: 14, sale: 60, demolition: 60 },
    },
    rentIncrease: { section: 's 44', minimumNotice: 60 },
    breachNotice: { section: 's 91ZA', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Prescribed Condition Report', url: 'https://www.consumer.vic.gov.au' },
      { type: 'tenancy_agreement', formNumber: 'Standard Form Lease', url: 'https://www.consumer.vic.gov.au' },
      { type: 'notice_to_vacate', formNumber: 'Notice to Vacate', url: 'https://www.consumer.vic.gov.au' },
    ],
    tribunalName: 'Victorian Civil and Administrative Tribunal (VCAT)',
    tribunalUrl: 'https://www.vcat.vic.gov.au',
    authorityName: 'Consumer Affairs Victoria',
    authorityUrl: 'https://www.consumer.vic.gov.au',
  },
  QLD: {
    name: 'Residential Tenancies and Rooming Accommodation Act 2008 (Qld)',
    state: 'QLD',
    conditionReport: {
      section: 's 65-67',
      description: 'Entry condition report (Form 1a) must be completed and copy given to tenant within 3 days.',
    },
    bondLodgement: {
      section: 's 116',
      authority: 'Residential Tenancies Authority (RTA)',
      url: 'https://www.rta.qld.gov.au',
    },
    noticeToVacate: {
      section: 's 326-330',
      periods: { end_of_fixed_term: 14, no_grounds_periodic: 60, breach: 14, sale: 30, demolition: 30 },
    },
    rentIncrease: { section: 's 91', minimumNotice: 60 },
    breachNotice: { section: 's 281', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Form 1a', url: 'https://www.rta.qld.gov.au/forms' },
      { type: 'tenancy_agreement', formNumber: 'Form 18a', url: 'https://www.rta.qld.gov.au/forms' },
      { type: 'notice_to_vacate', formNumber: 'Form 12', url: 'https://www.rta.qld.gov.au/forms' },
      { type: 'entry_notice', formNumber: 'Form 9', url: 'https://www.rta.qld.gov.au/forms' },
    ],
    tribunalName: 'Queensland Civil and Administrative Tribunal (QCAT)',
    tribunalUrl: 'https://www.qcat.qld.gov.au',
    authorityName: 'Residential Tenancies Authority (RTA)',
    authorityUrl: 'https://www.rta.qld.gov.au',
  },
  SA: {
    name: 'Residential Tenancies Act 1995 (SA)',
    state: 'SA',
    conditionReport: {
      section: 's 66',
      description: 'Condition report must be provided within 2 business days of tenant taking possession.',
    },
    bondLodgement: {
      section: 's 61',
      authority: 'Consumer and Business Services',
      url: 'https://www.cbs.sa.gov.au',
    },
    noticeToVacate: {
      section: 's 83-86',
      periods: { end_of_fixed_term: 28, no_grounds_periodic: 90, breach: 14, sale: 60, demolition: 60 },
    },
    rentIncrease: { section: 's 55', minimumNotice: 60 },
    breachNotice: { section: 's 80', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Form 2', url: 'https://www.cbs.sa.gov.au' },
      { type: 'tenancy_agreement', formNumber: 'Form 1', url: 'https://www.cbs.sa.gov.au' },
    ],
    tribunalName: 'South Australian Civil and Administrative Tribunal (SACAT)',
    tribunalUrl: 'https://www.sacat.sa.gov.au',
    authorityName: 'Consumer and Business Services',
    authorityUrl: 'https://www.cbs.sa.gov.au',
  },
  WA: {
    name: 'Residential Tenancies Act 1987 (WA)',
    state: 'WA',
    conditionReport: {
      section: 's 27C',
      description: 'Property condition report must be prepared by lessor and agreed by tenant at start of tenancy.',
    },
    bondLodgement: {
      section: 's 29',
      authority: 'Bond Administrator (Dept of Commerce)',
      url: 'https://www.commerce.wa.gov.au/consumer-protection/bond-administration',
    },
    noticeToVacate: {
      section: 's 61-68',
      periods: { end_of_fixed_term: 30, no_grounds_periodic: 60, breach: 14, sale: 30, demolition: 60 },
    },
    rentIncrease: { section: 's 30', minimumNotice: 60 },
    breachNotice: { section: 's 62', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Prescribed Property Condition Report', url: 'https://www.commerce.wa.gov.au' },
      { type: 'tenancy_agreement', formNumber: 'Residential Tenancy Agreement', url: 'https://www.commerce.wa.gov.au' },
    ],
    tribunalName: 'Magistrates Court of Western Australia',
    tribunalUrl: 'https://www.magistratescourt.wa.gov.au',
    authorityName: 'Department of Commerce',
    authorityUrl: 'https://www.commerce.wa.gov.au',
  },
  TAS: {
    name: 'Residential Tenancy Act 1997 (Tas)',
    state: 'TAS',
    conditionReport: {
      section: 's 23',
      description: 'Condition report provided to tenant within 2 days of tenancy start.',
    },
    bondLodgement: {
      section: 's 28',
      authority: 'Rental Deposit Authority',
      url: 'https://www.cbos.tas.gov.au',
    },
    noticeToVacate: {
      section: 's 42-46',
      periods: { end_of_fixed_term: 28, no_grounds_periodic: 42, breach: 14, sale: 42, demolition: 42 },
    },
    rentIncrease: { section: 's 22', minimumNotice: 60 },
    breachNotice: { section: 's 42', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Condition Report', url: 'https://www.cbos.tas.gov.au' },
    ],
    tribunalName: 'Residential Tenancy Commissioner',
    tribunalUrl: 'https://www.cbos.tas.gov.au',
    authorityName: 'Consumer, Building and Occupational Services',
    authorityUrl: 'https://www.cbos.tas.gov.au',
  },
  NT: {
    name: 'Residential Tenancies Act 1999 (NT)',
    state: 'NT',
    conditionReport: {
      section: 's 31',
      description: 'Condition report must be prepared by landlord and agreed by tenant.',
    },
    bondLodgement: {
      section: 's 25',
      authority: 'NT Consumer Affairs',
      url: 'https://consumeraffairs.nt.gov.au',
    },
    noticeToVacate: {
      section: 's 89-100',
      periods: { end_of_fixed_term: 14, no_grounds_periodic: 42, breach: 14, sale: 42, demolition: 42 },
    },
    rentIncrease: { section: 's 38', minimumNotice: 30 },
    breachNotice: { section: 's 89', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Condition Report', url: 'https://consumeraffairs.nt.gov.au' },
    ],
    tribunalName: 'Northern Territory Civil and Administrative Tribunal (NTCAT)',
    tribunalUrl: 'https://ntcat.nt.gov.au',
    authorityName: 'NT Consumer Affairs',
    authorityUrl: 'https://consumeraffairs.nt.gov.au',
  },
  ACT: {
    name: 'Residential Tenancies Act 1997 (ACT)',
    state: 'ACT',
    conditionReport: {
      section: 's 27',
      description: 'Condition report must be completed and signed by both parties.',
    },
    bondLodgement: {
      section: 's 23',
      authority: 'ACT Revenue Office',
      url: 'https://www.revenue.act.gov.au',
    },
    noticeToVacate: {
      section: 's 36-46',
      periods: { end_of_fixed_term: 26, no_grounds_periodic: 26, breach: 14, sale: 26, demolition: 26 },
    },
    rentIncrease: { section: 's 65', minimumNotice: 56 },
    breachNotice: { section: 's 46', remedyPeriod: 14 },
    prescribedForms: [
      { type: 'condition_report', formNumber: 'Schedule 1 Condition Report', url: 'https://www.accesscanberra.act.gov.au' },
    ],
    tribunalName: 'ACT Civil and Administrative Tribunal (ACAT)',
    tribunalUrl: 'https://www.acat.act.gov.au',
    authorityName: 'Access Canberra',
    authorityUrl: 'https://www.accesscanberra.act.gov.au',
  },
};

/**
 * Get detailed legislation references for a state.
 * Used by the agent to generate compliant documents.
 */
export function getDetailedStateLegislation(state: string): StateLegislation | null {
  return STATE_LEGISLATION[state.toUpperCase()] || null;
}

function getStateLegislation(state: string): string {
  const leg = STATE_LEGISLATION[state.toUpperCase()];
  if (leg) return leg.name;
  const map: Record<string, string> = {
    NSW: 'Residential Tenancies Act 2010 (NSW)',
    VIC: 'Residential Tenancies Act 1997 (Vic)',
    QLD: 'Residential Tenancies and Rooming Accommodation Act 2008 (Qld)',
    SA: 'Residential Tenancies Act 1995 (SA)',
    WA: 'Residential Tenancies Act 1987 (WA)',
    TAS: 'Residential Tenancy Act 1997 (Tas)',
    NT: 'Residential Tenancies Act 1999 (NT)',
    ACT: 'Residential Tenancies Act 1997 (ACT)',
  };
  return map[state.toUpperCase()] || 'the applicable Residential Tenancies Act';
}

function getNoticeTitle(type: NoticeType): string {
  switch (type) {
    case 'breach': return 'NOTICE OF BREACH';
    case 'entry': return 'NOTICE OF ENTRY';
    case 'rent_increase': return 'NOTICE OF RENT INCREASE';
    case 'termination': return 'NOTICE OF TERMINATION';
    case 'vacate': return 'NOTICE TO VACATE';
  }
}

export function generateNoticeHTML(data: NoticeData): string {
  const legislation = getStateLegislation(data.state);
  const title = getNoticeTitle(data.noticeType);

  let noticeBody = '';

  if (data.noticeType === 'breach') {
    noticeBody = `
    <div class="section">
      <h2>Details of Breach</h2>
      <p>${escapeHtml(data.breachDescription || 'Breach of tenancy agreement terms.')}</p>
      ${data.remedyDate ? `
      <div class="note">
        You are required to remedy this breach by <strong>${formatDateAU(data.remedyDate)}</strong>.
        Failure to remedy the breach may result in further action under the ${escapeHtml(legislation)}.
      </div>` : ''}
    </div>`;
  }

  if (data.noticeType === 'entry') {
    noticeBody = `
    <div class="section">
      <h2>Entry Details</h2>
      <table class="dt">
        <tr><td class="l">Date of Entry</td><td class="v">${data.entryDate ? formatDateAU(data.entryDate) : 'To be confirmed'}</td></tr>
        <tr><td class="l">Time</td><td class="v">${escapeHtml(data.entryTime || 'Between 8:00 AM and 6:00 PM')}</td></tr>
        <tr><td class="l">Reason</td><td class="v">${escapeHtml(data.entryReason || 'Routine inspection')}</td></tr>
      </table>
      <div class="note">
        This notice is given in accordance with the ${escapeHtml(legislation)}, which requires the landlord
        to provide reasonable notice before entering the premises.
      </div>
    </div>`;
  }

  if (data.noticeType === 'rent_increase') {
    noticeBody = `
    <div class="section">
      <h2>Rent Increase Details</h2>
      <table class="dt">
        <tr><td class="l">Current Rent</td><td class="v">${data.currentRent ? formatCurrency(data.currentRent) : 'N/A'} ${escapeHtml(data.rentFrequency || '')}</td></tr>
        <tr><td class="l">New Rent</td><td class="v">${data.newRent ? formatCurrency(data.newRent) : 'N/A'} ${escapeHtml(data.rentFrequency || '')}</td></tr>
        <tr><td class="l">Effective Date</td><td class="v">${data.effectiveDate ? formatDateAU(data.effectiveDate) : 'To be confirmed'}</td></tr>
      </table>
      <div class="note">
        This rent increase is given in accordance with the ${escapeHtml(legislation)}. If you believe
        this increase is excessive, you have the right to apply to the relevant tribunal for a review.
      </div>
    </div>`;
  }

  if (data.noticeType === 'termination' || data.noticeType === 'vacate') {
    noticeBody = `
    <div class="section">
      <h2>Termination Details</h2>
      <table class="dt">
        <tr><td class="l">Termination Date</td><td class="v">${data.terminationDate ? formatDateAU(data.terminationDate) : 'As per required notice period'}</td></tr>
        <tr><td class="l">Reason</td><td class="v">${escapeHtml(data.terminationReason || 'End of fixed term')}</td></tr>
      </table>
      <div class="note">
        This notice is given under the ${escapeHtml(legislation)}. You are required to vacate the premises
        by the date specified above. Please ensure the premises are left in the condition as outlined in
        the condition report, fair wear and tear excepted.
      </div>
    </div>`;
  }

  const body = `
    <div class="section">
      <h2>Parties</h2>
      <table class="dt">
        <tr><td class="l">From (Landlord)</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">To (Tenant)</td><td class="v">${escapeHtml(data.tenantName)}</td></tr>
        <tr><td class="l">Property</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>
        <tr><td class="l">Date of Notice</td><td class="v">${formatDateAU(data.issueDate)}</td></tr>
        <tr><td class="l">Applicable Legislation</td><td class="v">${escapeHtml(legislation)}</td></tr>
      </table>
    </div>

    ${noticeBody}

    ${data.additionalNotes ? `<div class="section"><h2>Additional Notes</h2><p>${escapeHtml(data.additionalNotes)}</p></div>` : ''}

    <div class="sig-block">
      <div class="sig-row">
        <div class="sig-party">
          <h3>Landlord (Owner)</h3>
          <div class="sig-line"></div>
          <div class="sig-label">Signature</div>
          <div class="sig-line"></div>
          <div class="sig-label">Name: ${escapeHtml(data.ownerName)}</div>
          <div class="sig-line"></div>
          <div class="sig-label">Date</div>
        </div>
      </div>
    </div>
  `;

  return wrapDocument(title, `${escapeHtml(data.state.toUpperCase())} — ${escapeHtml(legislation)}`, body);
}

// ============================================================
// Property Summary
// ============================================================

export interface PropertySummaryData {
  ownerName: string;
  propertyAddress: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  parking: number;
  rentAmount: number;
  rentFrequency: string;
  tenantName?: string;
  occupancyStatus: string;
  leaseStart?: string;
  leaseEnd?: string;
  totalIncome?: number;
  totalExpenses?: number;
  maintenanceCount?: number;
  complianceStatus?: string;
  notes?: string;
}

export function generatePropertySummaryHTML(data: PropertySummaryData): string {
  const body = `
    <div class="section">
      <h2>Property Details</h2>
      <table class="dt">
        <tr><td class="l">Address</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>
        <tr><td class="l">Type</td><td class="v">${escapeHtml(data.propertyType)}</td></tr>
        <tr><td class="l">Layout</td><td class="v">${data.bedrooms} bed, ${data.bathrooms} bath, ${data.parking} parking</td></tr>
        <tr><td class="l">Rent</td><td class="v">${formatCurrency(data.rentAmount)} ${escapeHtml(data.rentFrequency)}</td></tr>
        <tr><td class="l">Status</td><td class="v">${escapeHtml(data.occupancyStatus)}</td></tr>
      </table>
    </div>

    ${data.tenantName ? `
    <div class="section">
      <h2>Current Tenancy</h2>
      <table class="dt">
        <tr><td class="l">Tenant</td><td class="v">${escapeHtml(data.tenantName)}</td></tr>
        ${data.leaseStart ? `<tr><td class="l">Lease Start</td><td class="v">${formatDateAU(data.leaseStart)}</td></tr>` : ''}
        ${data.leaseEnd ? `<tr><td class="l">Lease End</td><td class="v">${formatDateAU(data.leaseEnd)}</td></tr>` : ''}
      </table>
    </div>` : ''}

    <div class="row" style="margin-bottom:16px">
      ${data.totalIncome !== undefined ? `
      <div class="col">
        <div class="summary-card">
          <div class="metric" style="color:#16A34A">${formatCurrency(data.totalIncome)}</div>
          <div class="metric-label">Total Income</div>
        </div>
      </div>` : ''}
      ${data.totalExpenses !== undefined ? `
      <div class="col">
        <div class="summary-card">
          <div class="metric" style="color:#DC2626">${formatCurrency(data.totalExpenses)}</div>
          <div class="metric-label">Total Expenses</div>
        </div>
      </div>` : ''}
      ${data.maintenanceCount !== undefined ? `
      <div class="col">
        <div class="summary-card">
          <div class="metric">${data.maintenanceCount}</div>
          <div class="metric-label">Maintenance Requests</div>
        </div>
      </div>` : ''}
    </div>

    ${data.complianceStatus ? `
    <div class="section">
      <h2>Compliance</h2>
      <p>${escapeHtml(data.complianceStatus)}</p>
    </div>` : ''}

    ${data.notes ? `<div class="note">${escapeHtml(data.notes)}</div>` : ''}
  `;

  return wrapDocument('Property Summary', escapeHtml(data.propertyAddress), body);
}

// ============================================================
// Portfolio Report
// ============================================================

export interface PortfolioReportData {
  ownerName: string;
  periodStart: string;
  periodEnd: string;
  totalProperties: number;
  occupiedProperties: number;
  totalIncome: number;
  totalExpenses: number;
  netProfit: number;
  properties: Array<{
    address: string;
    status: string;
    income: number;
    expenses: number;
  }>;
  notes?: string;
}

export function generatePortfolioReportHTML(data: PortfolioReportData): string {
  const occupancyRate = data.totalProperties > 0
    ? ((data.occupiedProperties / data.totalProperties) * 100).toFixed(1)
    : '0.0';

  const propertyRows = data.properties
    .map(p => `<tr>
      <td class="v">${escapeHtml(p.address)}</td>
      <td class="v">${escapeHtml(p.status)}</td>
      <td class="v" style="text-align:right">${formatCurrency(p.income)}</td>
      <td class="v" style="text-align:right">${formatCurrency(p.expenses)}</td>
      <td class="v" style="text-align:right;font-weight:600">${formatCurrency(p.income - p.expenses)}</td>
    </tr>`)
    .join('');

  const body = `
    <div class="section">
      <h2>Overview</h2>
      <table class="dt">
        <tr><td class="l">Owner</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">Period</td><td class="v">${formatDateShort(data.periodStart)} — ${formatDateShort(data.periodEnd)}</td></tr>
      </table>
    </div>

    <div class="row" style="margin-bottom:16px">
      <div class="col"><div class="summary-card"><div class="metric">${data.totalProperties}</div><div class="metric-label">Properties</div></div></div>
      <div class="col"><div class="summary-card"><div class="metric">${occupancyRate}%</div><div class="metric-label">Occupancy</div></div></div>
      <div class="col"><div class="summary-card"><div class="metric">${formatCurrency(data.netProfit)}</div><div class="metric-label">Net Profit</div></div></div>
    </div>

    <div class="section">
      <h2>Property Performance</h2>
      <table class="dt">
        <tr><th>Property</th><th>Status</th><th style="text-align:right">Income</th><th style="text-align:right">Expenses</th><th style="text-align:right">Net</th></tr>
        ${propertyRows}
        <tr style="font-weight:700;background:#F5F5F4">
          <td class="l" colspan="2">Total</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.totalIncome)}</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.totalExpenses)}</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(data.netProfit)}</td>
        </tr>
      </table>
    </div>

    ${data.notes ? `<div class="note">${escapeHtml(data.notes)}</div>` : ''}
  `;

  return wrapDocument('Portfolio Report', `${formatDateShort(data.periodStart)} — ${formatDateShort(data.periodEnd)}`, body);
}

// ============================================================
// Cash Flow Forecast
// ============================================================

export interface CashFlowForecastData {
  ownerName: string;
  propertyAddress?: string;
  forecastMonths: Array<{
    month: string;
    income: number;
    expenses: number;
    net: number;
  }>;
  assumptions?: string;
  notes?: string;
}

export function generateCashFlowForecastHTML(data: CashFlowForecastData): string {
  const monthRows = data.forecastMonths
    .map(m => `<tr>
      <td class="v">${escapeHtml(m.month)}</td>
      <td class="v" style="text-align:right">${formatCurrency(m.income)}</td>
      <td class="v" style="text-align:right">${formatCurrency(m.expenses)}</td>
      <td class="v" style="text-align:right;font-weight:600;color:${m.net >= 0 ? '#16A34A' : '#DC2626'}">${formatCurrency(m.net)}</td>
    </tr>`)
    .join('');

  const totalIncome = data.forecastMonths.reduce((s, m) => s + m.income, 0);
  const totalExpenses = data.forecastMonths.reduce((s, m) => s + m.expenses, 0);
  const totalNet = totalIncome - totalExpenses;

  const body = `
    <div class="section">
      <h2>Forecast Details</h2>
      <table class="dt">
        <tr><td class="l">Owner</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        ${data.propertyAddress ? `<tr><td class="l">Property</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>` : ''}
        <tr><td class="l">Period</td><td class="v">${data.forecastMonths.length} months</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Monthly Breakdown</h2>
      <table class="dt">
        <tr><th>Month</th><th style="text-align:right">Income</th><th style="text-align:right">Expenses</th><th style="text-align:right">Net</th></tr>
        ${monthRows}
        <tr style="font-weight:700;background:#F5F5F4">
          <td class="l">Total</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(totalIncome)}</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(totalExpenses)}</td>
          <td class="v" style="text-align:right;font-weight:700">${formatCurrency(totalNet)}</td>
        </tr>
      </table>
    </div>

    ${data.assumptions ? `<div class="section"><h2>Assumptions</h2><p>${escapeHtml(data.assumptions)}</p></div>` : ''}
    ${data.notes ? `<div class="note">${escapeHtml(data.notes)}</div>` : ''}
  `;

  return wrapDocument('Cash Flow Forecast', data.propertyAddress ? escapeHtml(data.propertyAddress) : 'Portfolio', body);
}

// ============================================================
// Compliance Certificate
// ============================================================

export interface ComplianceCertificateData {
  ownerName: string;
  propertyAddress: string;
  state: string;
  items: Array<{
    name: string;
    status: 'compliant' | 'overdue' | 'pending' | 'not_applicable';
    lastCompleted?: string;
    nextDue?: string;
    notes?: string;
  }>;
  overallStatus: string;
  generatedDate: string;
}

export function generateComplianceCertificateHTML(data: ComplianceCertificateData): string {
  const statusColor = (s: string) => {
    switch (s) {
      case 'compliant': return '#16A34A';
      case 'overdue': return '#DC2626';
      case 'pending': return '#CA8A04';
      default: return '#6B7280';
    }
  };

  const itemRows = data.items
    .map(item => `<tr>
      <td class="v">${escapeHtml(item.name)}</td>
      <td class="v" style="color:${statusColor(item.status)};font-weight:600">${item.status.replace('_', ' ').toUpperCase()}</td>
      <td class="v">${item.lastCompleted ? formatDateShort(item.lastCompleted) : '—'}</td>
      <td class="v">${item.nextDue ? formatDateShort(item.nextDue) : '—'}</td>
      <td class="v">${item.notes ? escapeHtml(item.notes) : '—'}</td>
    </tr>`)
    .join('');

  const compliantCount = data.items.filter(i => i.status === 'compliant').length;
  const overdueCount = data.items.filter(i => i.status === 'overdue').length;

  const body = `
    <div class="section">
      <h2>Property Details</h2>
      <table class="dt">
        <tr><td class="l">Owner</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">Property</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>
        <tr><td class="l">State</td><td class="v">${escapeHtml(data.state.toUpperCase())}</td></tr>
        <tr><td class="l">Overall Status</td><td class="v" style="font-weight:700">${escapeHtml(data.overallStatus)}</td></tr>
      </table>
    </div>

    <div class="row" style="margin-bottom:16px">
      <div class="col"><div class="summary-card"><div class="metric" style="color:#16A34A">${compliantCount}</div><div class="metric-label">Compliant</div></div></div>
      <div class="col"><div class="summary-card"><div class="metric" style="color:#DC2626">${overdueCount}</div><div class="metric-label">Overdue</div></div></div>
      <div class="col"><div class="summary-card"><div class="metric">${data.items.length}</div><div class="metric-label">Total Items</div></div></div>
    </div>

    <div class="section">
      <h2>Compliance Items</h2>
      <table class="dt">
        <tr><th>Item</th><th>Status</th><th>Last Completed</th><th>Next Due</th><th>Notes</th></tr>
        ${itemRows}
      </table>
    </div>

    <div class="note">
      This compliance summary is generated based on the information available to Casa. Property owners are
      ultimately responsible for ensuring all compliance obligations are met under the laws of ${escapeHtml(data.state.toUpperCase())}.
    </div>
  `;

  return wrapDocument('Compliance Certificate', escapeHtml(data.propertyAddress), body);
}

// ============================================================
// Generic Document (for "other" type or simple agent-generated docs)
// ============================================================

export interface GenericDocumentData {
  title: string;
  subtitle?: string;
  htmlBody: string;
  requiresSignature?: boolean;
  ownerName?: string;
  tenantName?: string;
}

export function generateGenericDocumentHTML(data: GenericDocumentData): string {
  let signatureBlock = '';
  if (data.requiresSignature) {
    signatureBlock = `
    <div class="sig-block">
      <div class="sig-row">
        ${data.ownerName ? `
        <div class="sig-party">
          <h3>Owner</h3>
          <div class="sig-line"></div>
          <div class="sig-label">Signature</div>
          <div class="sig-line"></div>
          <div class="sig-label">Name: ${escapeHtml(data.ownerName)}</div>
          <div class="sig-line"></div>
          <div class="sig-label">Date</div>
        </div>` : ''}
        ${data.tenantName ? `
        <div class="sig-party">
          <h3>Tenant</h3>
          <div class="sig-line"></div>
          <div class="sig-label">Signature</div>
          <div class="sig-line"></div>
          <div class="sig-label">Name: ${escapeHtml(data.tenantName)}</div>
          <div class="sig-line"></div>
          <div class="sig-label">Date</div>
        </div>` : ''}
      </div>
    </div>`;
  }

  const body = `
    <div class="section">
      ${data.htmlBody}
    </div>
    ${signatureBlock}
  `;

  return wrapDocument(data.title, data.subtitle || '', body);
}

// ============================================================
// QLD Form 12 — Entry Notice (RTRA Act 2008)
// ============================================================

export interface QLDForm12Data {
  propertyAddress: string;
  ownerName: string;
  ownerAddress: string;
  tenantNames: string[];
  entryDate: string;
  entryTimeFrom: string;
  entryTimeTo: string;
  entryReason: string;
  additionalNotes?: string;
}

export function generateQLDForm12HTML(data: QLDForm12Data): string {
  const tenantList = data.tenantNames.map(n => escapeHtml(n)).join(', ');
  const body = `
    <div class="note" style="background: #FEF3C7; border-left-color: #D97706;">
      <strong>Form 12 — Entry Notice</strong><br>
      Residential Tenancies and Rooming Accommodation Act 2008 (Qld), Section 192
    </div>

    <div class="section">
      <h2>Property Details</h2>
      <table class="dt">
        <tr><td class="l">Rental premises</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Parties</h2>
      <table class="dt">
        <tr><td class="l">Lessor / Agent</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">Lessor address</td><td class="v">${escapeHtml(data.ownerAddress)}</td></tr>
        <tr><td class="l">Tenant(s)</td><td class="v">${tenantList}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Entry Details</h2>
      <table class="dt">
        <tr><td class="l">Date of entry</td><td class="v">${formatDateAU(data.entryDate)}</td></tr>
        <tr><td class="l">Time of entry</td><td class="v">${escapeHtml(data.entryTimeFrom)} to ${escapeHtml(data.entryTimeTo)}</td></tr>
        <tr><td class="l">Reason for entry</td><td class="v">${escapeHtml(data.entryReason)}</td></tr>
        ${data.additionalNotes ? `<tr><td class="l">Additional notes</td><td class="v">${escapeHtml(data.additionalNotes)}</td></tr>` : ''}
      </table>
    </div>

    <div class="note">
      <strong>Notice requirements:</strong> Under the RTRA Act 2008, the lessor must give the tenant at least
      24 hours' written notice for most entry reasons, or at least 48 hours for a general inspection.
      Entry may only be between 8:00 am and 6:00 pm on a day that is not a public holiday.
    </div>

    <div class="sig-block">
      <div class="sig-row">
        <div class="sig-party">
          <h3>Lessor / Agent</h3>
          <div class="sig-line"></div>
          <div class="sig-label">Signature</div>
          <div class="sig-line"></div>
          <div class="sig-label">Name: ${escapeHtml(data.ownerName)}</div>
          <div class="sig-line"></div>
          <div class="sig-label">Date</div>
        </div>
      </div>
    </div>
  `;

  return wrapDocument(
    'Form 12 — Entry Notice',
    'Residential Tenancies and Rooming Accommodation Act 2008 (Qld)',
    body,
  );
}

// ============================================================
// QLD Form 13 — Notice of Rent Increase (RTRA Act 2008)
// ============================================================

export interface QLDForm13Data {
  propertyAddress: string;
  ownerName: string;
  ownerAddress: string;
  tenantNames: string[];
  currentRent: number;
  currentFrequency: string;
  newRent: number;
  newFrequency: string;
  effectiveDate: string;
  noticeDateGiven: string;
}

export function generateQLDForm13HTML(data: QLDForm13Data): string {
  const tenantList = data.tenantNames.map(n => escapeHtml(n)).join(', ');
  const increaseAmount = data.newRent - data.currentRent;
  const increasePercent = data.currentRent > 0
    ? ((increaseAmount / data.currentRent) * 100).toFixed(1)
    : '0.0';

  const body = `
    <div class="note" style="background: #FEF3C7; border-left-color: #D97706;">
      <strong>Form 13 — Notice of Rent Increase</strong><br>
      Residential Tenancies and Rooming Accommodation Act 2008 (Qld), Section 93
    </div>

    <div class="section">
      <h2>Property Details</h2>
      <table class="dt">
        <tr><td class="l">Rental premises</td><td class="v">${escapeHtml(data.propertyAddress)}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Parties</h2>
      <table class="dt">
        <tr><td class="l">Lessor / Agent</td><td class="v">${escapeHtml(data.ownerName)}</td></tr>
        <tr><td class="l">Lessor address</td><td class="v">${escapeHtml(data.ownerAddress)}</td></tr>
        <tr><td class="l">Tenant(s)</td><td class="v">${tenantList}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>Current Rent</h2>
      <table class="dt">
        <tr><td class="l">Current rent</td><td class="v">${formatCurrency(data.currentRent)}</td></tr>
        <tr><td class="l">Payment frequency</td><td class="v">${escapeHtml(data.currentFrequency)}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2>New Rent</h2>
      <table class="dt">
        <tr><td class="l">New rent</td><td class="v"><strong>${formatCurrency(data.newRent)}</strong></td></tr>
        <tr><td class="l">Payment frequency</td><td class="v">${escapeHtml(data.newFrequency)}</td></tr>
        <tr><td class="l">Increase amount</td><td class="v">${formatCurrency(increaseAmount)} (${increasePercent}%)</td></tr>
        <tr><td class="l">Effective from</td><td class="v"><strong>${formatDateAU(data.effectiveDate)}</strong></td></tr>
        <tr><td class="l">Date notice given</td><td class="v">${formatDateAU(data.noticeDateGiven)}</td></tr>
      </table>
    </div>

    <div class="note">
      <strong>Legal requirements (QLD):</strong><br>
      &bull; At least 2 months (60 days) written notice must be given before the increase takes effect.<br>
      &bull; Rent may be increased no more than once every 6 months.<br>
      &bull; The tenant may apply to QCAT if they believe the increase is excessive.<br>
      &bull; This notice must be given using this approved form (Form 13).
    </div>

    <div class="note">
      <strong>Tenant rights:</strong> If you believe this rent increase is excessive, you may apply
      to the Queensland Civil and Administrative Tribunal (QCAT) to have the increase reviewed.
      You must apply within 30 days of receiving this notice. Contact QCAT on 1300 753 228 or
      visit www.qcat.qld.gov.au.
    </div>

    <div class="sig-block">
      <div class="sig-row">
        <div class="sig-party">
          <h3>Lessor / Agent</h3>
          <div class="sig-line"></div>
          <div class="sig-label">Signature</div>
          <div class="sig-line"></div>
          <div class="sig-label">Name: ${escapeHtml(data.ownerName)}</div>
          <div class="sig-line"></div>
          <div class="sig-label">Date</div>
        </div>
      </div>
    </div>
  `;

  return wrapDocument(
    'Form 13 — Notice of Rent Increase',
    'Residential Tenancies and Rooming Accommodation Act 2008 (Qld)',
    body,
  );
}
