// Send Breach Notice - Supabase Edge Function
// Casa - Mission 08: Arrears & Late Payment Management
//
// Generates and sends state-compliant breach notices for serious arrears.
// Breach notices have specific legal requirements per Australian state:
// - NSW: 14 days to remedy (Residential Tenancies Act 2010)
// - VIC: 14 days to remedy (Residential Tenancies Act 1997)
// - QLD: 7 days to remedy (Residential Tenancies and Rooming Accommodation Act 2008)
//
// This is a HIGH-RISK action that should only be triggered with explicit owner consent.

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { corsHeaders, handleCors } from '../_shared/cors.ts';
import { getServiceClient } from '../_shared/supabase.ts';
import { sendEmail } from '../_shared/sendgrid.ts';

interface BreachNoticeRequest {
  arrearsRecordId: string;
  deliveryMethod: 'email' | 'post' | 'both';
  ownerConfirmation: boolean; // Must be true to proceed
}

// State-specific breach notice requirements
const STATE_REQUIREMENTS: Record<string, {
  remedyDays: number;
  legislation: string;
  noticeTitle: string;
}> = {
  NSW: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 2010 (NSW)',
    noticeTitle: 'Notice of Breach of Residential Tenancy Agreement',
  },
  VIC: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 1997 (VIC)',
    noticeTitle: 'Notice to Vacate - Rent Arrears',
  },
  QLD: {
    remedyDays: 7,
    legislation: 'Residential Tenancies and Rooming Accommodation Act 2008 (QLD)',
    noticeTitle: 'Notice to Remedy Breach',
  },
  SA: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 1995 (SA)',
    noticeTitle: 'Notice of Breach',
  },
  WA: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 1987 (WA)',
    noticeTitle: 'Notice of Breach of Agreement',
  },
  TAS: {
    remedyDays: 14,
    legislation: 'Residential Tenancy Act 1997 (TAS)',
    noticeTitle: 'Notice of Breach',
  },
  NT: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 1999 (NT)',
    noticeTitle: 'Notice of Breach',
  },
  ACT: {
    remedyDays: 14,
    legislation: 'Residential Tenancies Act 1997 (ACT)',
    noticeTitle: 'Notice of Breach',
  },
};

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-AU', {
    style: 'currency',
    currency: 'AUD',
  }).format(amount);
}

function formatDate(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-AU', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

function generateBreachNoticeContent(
  state: string,
  data: {
    tenantName: string;
    propertyAddress: string;
    totalArrears: number;
    daysOverdue: number;
    firstOverdueDate: string;
    ownerName: string;
    remedyDate: string;
  }
): { subject: string; htmlContent: string; textContent: string } {
  const stateReq = STATE_REQUIREMENTS[state] || STATE_REQUIREMENTS.NSW;

  const textContent = `
${stateReq.noticeTitle.toUpperCase()}
Pursuant to the ${stateReq.legislation}

TO: ${data.tenantName}
PROPERTY: ${data.propertyAddress}
DATE OF NOTICE: ${formatDate(new Date())}

NOTICE OF BREACH - NON-PAYMENT OF RENT

You are hereby notified that you are in breach of your Residential Tenancy Agreement for failure to pay rent when due.

PARTICULARS OF BREACH:

Rent arrears as at ${formatDate(new Date())}: ${formatCurrency(data.totalArrears)}
Days overdue: ${data.daysOverdue} days
First overdue payment date: ${formatDate(data.firstOverdueDate)}

REMEDY REQUIRED:

You must pay the full amount of ${formatCurrency(data.totalArrears)} within ${stateReq.remedyDays} days of the date of this notice.

REMEDY DATE: ${data.remedyDate}

CONSEQUENCE OF FAILURE TO REMEDY:

If you fail to remedy this breach by paying the full amount owing by the remedy date, the landlord may apply to the relevant tribunal for:
- An order terminating your tenancy agreement; and/or
- An order for possession of the premises; and/or
- An order for payment of the rent arrears.

If you are experiencing financial hardship, you are encouraged to contact the landlord immediately to discuss potential payment arrangements.

LANDLORD/AGENT DETAILS:
${data.ownerName}

This notice has been issued in accordance with the ${stateReq.legislation}.

---
This notice was generated by Casa Property Management.
  `.trim();

  const htmlContent = `
    <div style="font-family: 'Times New Roman', serif; max-width: 800px; margin: 0 auto; padding: 40px; background: white;">
      <div style="border: 2px solid #1B2B4B; padding: 30px;">
        <h1 style="text-align: center; color: #1B2B4B; font-size: 24px; margin-bottom: 10px; text-transform: uppercase;">
          ${stateReq.noticeTitle}
        </h1>
        <p style="text-align: center; color: #6B7280; font-size: 14px; margin-bottom: 30px;">
          Pursuant to the ${stateReq.legislation}
        </p>

        <table style="width: 100%; margin-bottom: 30px; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 0; color: #6B7280; width: 150px;">TO:</td>
            <td style="padding: 8px 0; font-weight: bold;">${data.tenantName}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #6B7280;">PROPERTY:</td>
            <td style="padding: 8px 0; font-weight: bold;">${data.propertyAddress}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #6B7280;">DATE OF NOTICE:</td>
            <td style="padding: 8px 0; font-weight: bold;">${formatDate(new Date())}</td>
          </tr>
        </table>

        <h2 style="color: #DC2626; font-size: 18px; border-bottom: 1px solid #DC2626; padding-bottom: 10px;">
          NOTICE OF BREACH - NON-PAYMENT OF RENT
        </h2>

        <p style="line-height: 1.8; color: #1B2B4B;">
          You are hereby notified that you are in breach of your Residential Tenancy Agreement for failure to pay rent when due.
        </p>

        <h3 style="color: #1B2B4B; font-size: 16px; margin-top: 30px;">PARTICULARS OF BREACH:</h3>
        <div style="background: #FEF2F2; border-left: 4px solid #DC2626; padding: 20px; margin: 20px 0;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #6B7280;">Rent arrears as at ${formatDate(new Date())}:</td>
              <td style="padding: 8px 0; font-weight: bold; color: #DC2626; font-size: 20px; text-align: right;">
                ${formatCurrency(data.totalArrears)}
              </td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #6B7280;">Days overdue:</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.daysOverdue} days</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #6B7280;">First overdue payment date:</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${formatDate(data.firstOverdueDate)}</td>
            </tr>
          </table>
        </div>

        <h3 style="color: #1B2B4B; font-size: 16px; margin-top: 30px;">REMEDY REQUIRED:</h3>
        <p style="line-height: 1.8; color: #1B2B4B;">
          You must pay the full amount of <strong>${formatCurrency(data.totalArrears)}</strong> within
          <strong>${stateReq.remedyDays} days</strong> of the date of this notice.
        </p>

        <div style="background: #1B2B4B; color: white; padding: 20px; text-align: center; margin: 20px 0;">
          <p style="margin: 0; font-size: 14px;">REMEDY DATE</p>
          <p style="margin: 10px 0 0 0; font-size: 24px; font-weight: bold;">${data.remedyDate}</p>
        </div>

        <h3 style="color: #1B2B4B; font-size: 16px; margin-top: 30px;">CONSEQUENCE OF FAILURE TO REMEDY:</h3>
        <p style="line-height: 1.8; color: #1B2B4B;">
          If you fail to remedy this breach by paying the full amount owing by the remedy date, the landlord may apply to the relevant tribunal for:
        </p>
        <ul style="line-height: 1.8; color: #1B2B4B;">
          <li>An order terminating your tenancy agreement; and/or</li>
          <li>An order for possession of the premises; and/or</li>
          <li>An order for payment of the rent arrears.</li>
        </ul>

        <div style="background: #F3F4F6; padding: 20px; margin: 30px 0; border-radius: 8px;">
          <p style="margin: 0; color: #6B7280; font-size: 14px;">
            <strong>Financial Hardship:</strong> If you are experiencing financial hardship, you are encouraged to contact the landlord immediately to discuss potential payment arrangements.
          </p>
        </div>

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB;">
          <p style="color: #6B7280; font-size: 14px; margin-bottom: 5px;">LANDLORD/AGENT:</p>
          <p style="font-weight: bold; margin: 0;">${data.ownerName}</p>
        </div>

        <p style="color: #9CA3AF; font-size: 12px; margin-top: 30px; text-align: center;">
          This notice has been issued in accordance with the ${stateReq.legislation}.
        </p>
      </div>
      <p style="color: #9CA3AF; font-size: 11px; text-align: center; margin-top: 20px;">
        Generated by Casa Property Management
      </p>
    </div>
  `;

  return {
    subject: `${stateReq.noticeTitle} - ${data.propertyAddress}`,
    htmlContent,
    textContent,
  };
}

serve(async (req: Request) => {
  // Handle CORS preflight
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  try {
    const supabase = getServiceClient();
    const body: BreachNoticeRequest = await req.json();

    // Validate required fields
    if (!body.arrearsRecordId) {
      return new Response(
        JSON.stringify({ error: 'arrearsRecordId is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!body.ownerConfirmation) {
      return new Response(
        JSON.stringify({ error: 'Owner confirmation is required to send breach notice' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Verify authorization
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Authorization required' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user } } = await supabase.auth.getUser(token);

    if (!user) {
      return new Response(
        JSON.stringify({ error: 'Invalid token' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Fetch arrears record with all related data
    const { data: arrears, error: arrearsError } = await supabase
      .from('arrears_records')
      .select(`
        id,
        tenancy_id,
        tenant_id,
        days_overdue,
        total_overdue,
        first_overdue_date,
        tenancies!inner(
          id,
          properties!inner(
            id,
            address_line_1,
            address_line_2,
            suburb,
            state,
            postcode,
            owner_id,
            profiles!properties_owner_id_fkey(
              full_name,
              email
            )
          )
        ),
        profiles!arrears_records_tenant_id_fkey(
          id,
          full_name,
          email
        )
      `)
      .eq('id', body.arrearsRecordId)
      .single();

    if (arrearsError || !arrears) {
      return new Response(
        JSON.stringify({ error: 'Arrears record not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const tenancy = (arrears as any).tenancies;
    const property = tenancy?.properties;
    const owner = property?.profiles;
    const tenant = (arrears as any).profiles;

    // Verify the requesting user is the owner
    if (property?.owner_id !== user.id) {
      return new Response(
        JSON.stringify({ error: 'You do not have permission to send breach notices for this property' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Verify tenant has email
    if (!tenant?.email) {
      return new Response(
        JSON.stringify({ error: 'Tenant email not found' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get state-specific requirements
    const state = property?.state || 'NSW';
    const stateReq = STATE_REQUIREMENTS[state] || STATE_REQUIREMENTS.NSW;

    // Calculate remedy date
    const remedyDate = new Date();
    remedyDate.setDate(remedyDate.getDate() + stateReq.remedyDays);

    // Build property address
    const propertyAddress = [
      property?.address_line_1,
      property?.address_line_2,
      property?.suburb,
      property?.state,
      property?.postcode,
    ].filter(Boolean).join(', ');

    // Generate breach notice content
    const noticeContent = generateBreachNoticeContent(state, {
      tenantName: tenant.full_name || 'Tenant',
      propertyAddress,
      totalArrears: arrears.total_overdue,
      daysOverdue: arrears.days_overdue,
      firstOverdueDate: arrears.first_overdue_date,
      ownerName: owner?.full_name || 'Property Owner',
      remedyDate: formatDate(remedyDate),
    });

    // Send email if requested
    let emailSent = false;
    let emailError: string | undefined;

    if (body.deliveryMethod === 'email' || body.deliveryMethod === 'both') {
      const emailResult = await sendEmail({
        to: tenant.email,
        toName: tenant.full_name,
        subject: noticeContent.subject,
        htmlContent: noticeContent.htmlContent,
        textContent: noticeContent.textContent,
      });

      emailSent = emailResult.success;
      emailError = emailResult.error;
    }

    // Log the action
    await supabase.from('arrears_actions').insert({
      arrears_record_id: arrears.id,
      action_type: 'breach_notice',
      description: `Breach notice sent (${state} - ${stateReq.remedyDays} day remedy period). Delivery: ${body.deliveryMethod}. Remedy date: ${formatDate(remedyDate)}`,
      template_used: `Breach Notice (${state})`,
      sent_to: tenant.email,
      sent_at: new Date().toISOString(),
      delivered: emailSent,
      performed_by: user.id,
      is_automated: false,
      metadata: {
        state,
        remedy_days: stateReq.remedyDays,
        remedy_date: remedyDate.toISOString(),
        delivery_method: body.deliveryMethod,
        legislation: stateReq.legislation,
        email_sent: emailSent,
        email_error: emailError,
      },
    });

    console.log(`Breach notice sent for arrears ${arrears.id} to ${tenant.email}`);

    return new Response(
      JSON.stringify({
        success: true,
        arrearsRecordId: arrears.id,
        tenantEmail: tenant.email,
        state,
        remedyDays: stateReq.remedyDays,
        remedyDate: remedyDate.toISOString(),
        deliveryMethod: body.deliveryMethod,
        emailSent,
        emailError,
        notice: {
          subject: noticeContent.subject,
          // Don't return full content in response for security
        },
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: any) {
    console.error('Breach notice error:', error);
    return new Response(
      JSON.stringify({ error: error.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
